remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
title: "Kunal's Research Blog"
permalink: /blog/:title/
description: "Sharing insights on AI, security, and research."
