# Site Settings
title: "Kunal's Research Blog"
description: "Sharing insights on AI, security, and research."
url: "https://kunal-crl-bel.github.io"
baseurl: ""  # Leave blank unless using a subpath

# Theme & Plugins
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-feed
  - jekyll-paginate
  - jekyll-include-cache  # Prevents 'include_cached' errors

# Blog Permalinks & Pagination
paginate: 5
paginate_path: "/blog/page:num/"
permalink: /blog/:year/:month/:day/:title/

# Homepage Layout (Fixes missing main page)
defaults:
  - scope:
      path: ""
    values:
      layout: home

# Navigation Links (Fixing structure)
nav_links:
  Home: 
    url: "/"
  Blog: 
    url: "/blog/"
  About: 
    url: "/about/"
  Contact: 
    url: "/contact/"

# SEO & Google Analytics
google_analytics: "G-F7V6NTL8CS"
github_username: "kunal-crl-bel"

# Blog Settings
show_excerpts: true
excerpt_separator: <!--more-->

# Archive Pages
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    category: "/categories/:name/"
    tag: "/tags/:name/"
