# Site Settings
title: "Kunal's Research Blog"
description: "Sharing insights on AI, security, and research."
url: "https://kunal-crl-bel.github.io"
baseurl: ""  # Keep blank unless using a subpath

# Theme & Plugins
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-feed
  - jekyll-paginate
  - jekyll-include-cache  # Fixes 'include_cached' error

# Pagination & Blog URLs
paginate: 5
paginate_path: "/blog/page:num/"
permalink: /blog/:year/:month/:day/:title/

# Homepage Layout
defaults:
  - scope:
      path: ""
    values:
      layout: home

# Navigation Links
nav_links:
  Home: "/"
  Blog: "/blog/"
  About: "/about/"
  Contact: "/contact/"

# SEO & Google Analytics
google_analytics: "G-F7V6NTL8CS"
github_username: "kunal-crl-bel"

# Archives for Categories & Tags
jekyll-archives:
  enabled: 
    - categories
    - tags
  layout: archive
  permalinks:
    category: "/categories/:name/"
    tag: "/tags/:name/"
