# Site Settings
title: "Kunal's Research Blog"
description: "Sharing insights on AI, security, and research."
url: "https://kunal-crl-bel.github.io"
baseurl: ""  # Keep blank unless using a subpath

# Theme & Plugins
remote_theme: "mmistakes/minimal-mistakes"
theme: "minimal-mistakes-jekyll"  # Ensure compatibility with local builds
minimal_mistakes_skin: "default"  # Ensures correct styling

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-feed
  - jekyll-paginate
  - jekyll-include-cache  # Fixes 'include_cached' error

# Pagination & Blog URLs
paginate: 5
paginate_path: "/blog/page:num/"
permalink: "/blog/:year/:month/:day/:title/"

# Homepage Layout
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: home
      author_profile: true

# Navigation Links
navigation:
  - title: "Home"
    url: "/"
  - title: "Blog"
    url: "/blog/"
  - title: "About"
    url: "/about/"
  - title: "Contact"
    url: "/contact/"

# SEO & Google Analytics
google_analytics: "G-F7V6NTL8CS"
github_username: "kunal-crl-bel"

# Archives for Categories & Tags
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: "archive"
  permalinks:
    category: "/categories/:name/"
    tag: "/tags/:name/"
