remote_theme: "beautiful-jekyll/beautiful-jekyll"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
title: "Kunal's Research Blog"
permalink: /blog/:title/
description: "Sharing insights on AI, security, and research."
