remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
title: "Kunal's Research Blog"
description: "Research and insights on cybersecurity, AI, and more."

# SEO & Google Analytics
google_analytics: "G-F7V6NTL8CS"
github_username: "kunal-crl-bel"
